// Generated by CoffeeScript 1.3.3
(function() {

  window.App = (function() {

    function App() {
      this.searchBox = new SearchBox(this);
      this.hashReader = new HashReader(this);
    }

    return App;

  })();

}).call(this);
