// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    $.extend($.expr[":"], {
      "containsNC": function(elem, i, match, array) {
        return (elem.textContent || elem.innerText || "").toLowerCase().indexOf((match[3] || "").toLowerCase()) >= 0;
      }
    });
    return window.app = new App;
  });

}).call(this);
