// Generated by CoffeeScript 1.3.3
(function() {

  describe("hashReader", function() {
    return it("exists", function() {
      return expect(window.app.hashReader).toBeDefined();
    });
  });

}).call(this);
