// Generated by CoffeeScript 1.3.3
(function() {

  describe("preferenceManager", function() {
    it("exists", function() {
      return expect(window.app.preferenceManager).toBeDefined();
    });
    return it("does nothing when localStorage is missing", function() {
      window.localStorage = null;
      return expect(window.app.preferenceManager.active).toBe(false);
    });
  });

}).call(this);
